package com.audriuskumpis.mybatis.model;

import lombok.Getter;
import lombok.Setter;

@Getter
@Setter
public class Student {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.STUDENT.ID
     *
     * @mbg.generated Mon May 02 20:18:14 EEST 2022
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.STUDENT.FULL_NAME
     *
     * @mbg.generated Mon May 02 20:18:14 EEST 2022
     */
    private String fullName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.STUDENT.COURSE_ID
     *
     * @mbg.generated Mon May 02 20:18:14 EEST 2022
     */
    private Integer courseId;

    private Course course;
}