package com.audriuskumpis.mybatis.model;

public class Student {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.STUDENT.ID
     *
     * @mbg.generated Tue Apr 19 19:58:33 EEST 2022
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.STUDENT.FULL_NAME
     *
     * @mbg.generated Tue Apr 19 19:58:33 EEST 2022
     */
    private String fullName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.STUDENT.COURSE_ID
     *
     * @mbg.generated Tue Apr 19 19:58:33 EEST 2022
     */
    private Integer courseId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.STUDENT.ID
     *
     * @return the value of PUBLIC.STUDENT.ID
     *
     * @mbg.generated Tue Apr 19 19:58:33 EEST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.STUDENT.ID
     *
     * @param id the value for PUBLIC.STUDENT.ID
     *
     * @mbg.generated Tue Apr 19 19:58:33 EEST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.STUDENT.FULL_NAME
     *
     * @return the value of PUBLIC.STUDENT.FULL_NAME
     *
     * @mbg.generated Tue Apr 19 19:58:33 EEST 2022
     */
    public String getFullName() {
        return fullName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.STUDENT.FULL_NAME
     *
     * @param fullName the value for PUBLIC.STUDENT.FULL_NAME
     *
     * @mbg.generated Tue Apr 19 19:58:33 EEST 2022
     */
    public void setFullName(String fullName) {
        this.fullName = fullName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.STUDENT.COURSE_ID
     *
     * @return the value of PUBLIC.STUDENT.COURSE_ID
     *
     * @mbg.generated Tue Apr 19 19:58:33 EEST 2022
     */
    public Integer getCourseId() {
        return courseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.STUDENT.COURSE_ID
     *
     * @param courseId the value for PUBLIC.STUDENT.COURSE_ID
     *
     * @mbg.generated Tue Apr 19 19:58:33 EEST 2022
     */
    public void setCourseId(Integer courseId) {
        this.courseId = courseId;
    }
}