package com.audriuskumpis.mybatis.dao;

import com.audriuskumpis.mybatis.model.Instructor;
import org.mybatis.cdi.Mapper;

import java.util.List;

@Mapper
public interface InstructorMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.INSTRUCTOR
     *
     * @mbg.generated Tue Apr 19 19:58:33 EEST 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.INSTRUCTOR
     *
     * @mbg.generated Tue Apr 19 19:58:33 EEST 2022
     */
    int insert(Instructor record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.INSTRUCTOR
     *
     * @mbg.generated Tue Apr 19 19:58:33 EEST 2022
     */
    Instructor selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.INSTRUCTOR
     *
     * @mbg.generated Tue Apr 19 19:58:33 EEST 2022
     */
    List<Instructor> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.INSTRUCTOR
     *
     * @mbg.generated Tue Apr 19 19:58:33 EEST 2022
     */
    int updateByPrimaryKey(Instructor record);
}